### ISSUE TITLE
pika crashes about once per hour without any perceivable reason

### ISSUE THREAD

**Issue by phish108** [sustainability-zhaw/sdg-indexer#14]
@stlozhaw it seems that the sdg indexer dies approx. once per hour and sometimes faster without any messages being logged. 

The shortest crash duration was 10 min. the longest keep alive was 3h. 

That the time of a crash, I see the following notification from rabbitmq. 

```
2023-06-21 20:51:48.644278+00:00 [warning] <0.9130.0> closing AMQP connection <0.9130.0> (10.0.2.248:60608 -> 10.0.2.6:5672, vhost: '/', user: 'guest'):
2023-06-21 20:51:48.644278+00:00 [warning] <0.9130.0> client unexpectedly closed TCP connection
```

The indexer's own logs read as follows: 

```
2023-06-21T20:51:48.650591279Z sdg_indexer.1.qjhr16h4vp37    | ERROR: pika.adapters.utils.io_services_utils: 2023-06-21 20:51:48,649: _AsyncBaseTransport._consume() failed, aborting connection: error=ConnectionResetError(104, 'Connection reset by peer'); sock=<socket.socket fd=7, family=2, type=1, proto=6, laddr=('10.0.2.124', 60608)>; Caller's stack:
2023-06-21T20:51:48.650619874Z sdg_indexer.1.qjhr16h4vp37    | Traceback (most recent call last):
2023-06-21T20:51:48.650628272Z sdg_indexer.1.qjhr16h4vp37    |   File "/usr/local/lib/python3.11/site-packages/pika/adapters/utils/io_services_utils.py", line 1047, in _on_socket_readable
2023-06-21T20:51:48.650634631Z sdg_indexer.1.qjhr16h4vp37    |     self._consume()
2023-06-21T20:51:48.650640227Z sdg_indexer.1.qjhr16h4vp37    |   File "/usr/local/lib/python3.11/site-packages/pika/adapters/utils/io_services_utils.py", line 791, in _consume
2023-06-21T20:51:48.650646172Z sdg_indexer.1.qjhr16h4vp37    |     data = self._sigint_safe_recv(self._sock, self._MAX_RECV_BYTES)
2023-06-21T20:51:48.650651664Z sdg_indexer.1.qjhr16h4vp37    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-06-21T20:51:48.650657090Z sdg_indexer.1.qjhr16h4vp37    |   File "/usr/local/lib/python3.11/site-packages/pika/adapters/utils/io_services_utils.py", line 79, in retry_sigint_wrap
2023-06-21T20:51:48.650662928Z sdg_indexer.1.qjhr16h4vp37    |     return func(*args, **kwargs)
2023-06-21T20:51:48.650668296Z sdg_indexer.1.qjhr16h4vp37    |            ^^^^^^^^^^^^^^^^^^^^^
2023-06-21T20:51:48.650673659Z sdg_indexer.1.qjhr16h4vp37    |   File "/usr/local/lib/python3.11/site-packages/pika/adapters/utils/io_services_utils.py", line 846, in _sigint_safe_recv
2023-06-21T20:51:48.650679573Z sdg_indexer.1.qjhr16h4vp37    |     return sock.recv(max_bytes)
2023-06-21T20:51:48.650685039Z sdg_indexer.1.qjhr16h4vp37    |            ^^^^^^^^^^^^^^^^^^^^
2023-06-21T20:51:48.650690527Z sdg_indexer.1.qjhr16h4vp37    | ConnectionResetError: [Errno 104] Connection reset by peer
2023-06-21T20:51:48.650695991Z sdg_indexer.1.qjhr16h4vp37    | Traceback (most recent call last):
2023-06-21T20:51:48.650701373Z sdg_indexer.1.qjhr16h4vp37    |   File "/usr/local/lib/python3.11/site-packages/pika/adapters/utils/io_services_utils.py", line 1047, in _on_socket_readable
2023-06-21T20:51:48.650707043Z sdg_indexer.1.qjhr16h4vp37    |     self._consume()
2023-06-21T20:51:48.650712347Z sdg_indexer.1.qjhr16h4vp37    |   File "/usr/local/lib/python3.11/site-packages/pika/adapters/utils/io_services_utils.py", line 791, in _consume
2023-06-21T20:51:48.650717903Z sdg_indexer.1.qjhr16h4vp37    |     data = self._sigint_safe_recv(self._sock, self._MAX_RECV_BYTES)
2023-06-21T20:51:48.650723336Z sdg_indexer.1.qjhr16h4vp37    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-06-21T20:51:48.650728838Z sdg_indexer.1.qjhr16h4vp37    |   File "/usr/local/lib/python3.11/site-packages/pika/adapters/utils/io_services_utils.py", line 79, in retry_sigint_wrap
2023-06-21T20:51:48.650734607Z sdg_indexer.1.qjhr16h4vp37    |     return func(*args, **kwargs)
2023-06-21T20:51:48.650740006Z sdg_indexer.1.qjhr16h4vp37    |            ^^^^^^^^^^^^^^^^^^^^^
2023-06-21T20:51:48.650745307Z sdg_indexer.1.qjhr16h4vp37    |   File "/usr/local/lib/python3.11/site-packages/pika/adapters/utils/io_services_utils.py", line 846, in _sigint_safe_recv
2023-06-21T20:51:48.650764214Z sdg_indexer.1.qjhr16h4vp37    |     return sock.recv(max_bytes)
2023-06-21T20:51:48.650770763Z sdg_indexer.1.qjhr16h4vp37    |            ^^^^^^^^^^^^^^^^^^^^
2023-06-21T20:51:48.650774877Z sdg_indexer.1.qjhr16h4vp37    | ConnectionResetError: [Errno 104] Connection reset by peer
2023-06-21T20:51:48.650858033Z sdg_indexer.1.qjhr16h4vp37    | ERROR: pika.adapters.base_connection: 2023-06-21 20:51:48,650: connection_lost: StreamLostError: ("Stream connection lost: ConnectionResetError(104, 'Connection reset by peer')",)
2023-06-21T20:51:48.651283815Z sdg_indexer.1.qjhr16h4vp37    | ERROR: pika.adapters.blocking_connection: 2023-06-21 20:51:48,651: Unexpected connection close detected: StreamLostError: ("Stream connection lost: ConnectionResetError(104, 'Connection reset by peer')",)
2023-06-21T20:51:48.651385740Z sdg_indexer.1.qjhr16h4vp37    | Traceback (most recent call last):
2023-06-21T20:51:48.651399314Z sdg_indexer.1.qjhr16h4vp37    |   File "/app/main.py", line 79, in <module>
2023-06-21T20:51:48.651492826Z sdg_indexer.1.qjhr16h4vp37    |     main()
2023-06-21T20:51:48.651559621Z sdg_indexer.1.qjhr16h4vp37    |   File "/app/main.py", line 71, in main
2023-06-21T20:51:48.651607955Z sdg_indexer.1.qjhr16h4vp37    |     channel.start_consuming()
2023-06-21T20:51:48.651669384Z sdg_indexer.1.qjhr16h4vp37    |   File "/usr/local/lib/python3.11/site-packages/pika/adapters/blocking_connection.py", line 1883, in start_consuming
2023-06-21T20:51:48.652172353Z sdg_indexer.1.qjhr16h4vp37    |     self._process_data_events(time_limit=None)
2023-06-21T20:51:48.652188691Z sdg_indexer.1.qjhr16h4vp37    |   File "/usr/local/lib/python3.11/site-packages/pika/adapters/blocking_connection.py", line 2044, in _process_data_events
2023-06-21T20:51:48.652723292Z sdg_indexer.1.qjhr16h4vp37    |     self.connection.process_data_events(time_limit=time_limit)
2023-06-21T20:51:48.652739595Z sdg_indexer.1.qjhr16h4vp37    |   File "/usr/local/lib/python3.11/site-packages/pika/adapters/blocking_connection.py", line 842, in process_data_events
2023-06-21T20:51:48.653009787Z sdg_indexer.1.qjhr16h4vp37    |     self._flush_output(common_terminator)
2023-06-21T20:51:48.653026272Z sdg_indexer.1.qjhr16h4vp37    |   File "/usr/local/lib/python3.11/site-packages/pika/adapters/blocking_connection.py", line 523, in _flush_output
2023-06-21T20:51:48.653146157Z sdg_indexer.1.qjhr16h4vp37    |     raise self._closed_result.value.error
2023-06-21T20:51:48.653205606Z sdg_indexer.1.qjhr16h4vp37    | pika.exceptions.StreamLostError: Stream connection lost: ConnectionResetError(104, 'Connection reset by peer')
```

While the service is up, it receives no messages at all

**Comment by phish108** [comment]
This issue is unrelated to the indexer and appears every 45 Minutes on all services that use `pika`

**Comment by phish108** [comment]
no more crashes found in the logs since [e9f2748](https://github.com/sustainability-zhaw/sdg-indexer/commit/e9f274814407acc5cb2344af6cdf9bbcaa53eaab)
